title: “Jekyll 4”学习
description: 谢谢你！
include:
  - '_test_include.yml'

tweets:
  - 2022:
    - 6:
      - 16:
          data from config
          y22 m6 d16
          some content
      - 17:
          y22m6d17 y22m6d17
  - 2023:
    - 6:
      - 16:
          some content
          1616 16 16
      - 17:
          17171717
          some content 2
          some content 333

site_field: '1245'
site_array:
  - site array 123
  - 456

collections:
  测试集合1:
    type: post
    post: true
    output: true

defaults:
  - scope:
      path: _测试集合1
    values:
      output: true

  - scope:
      path: ""
      type: "测试集合1"
    values:
      layout: "post"
  - scope:
      path: README.md
    values:
      layout: home
  - scope:
      path:
    values:
      layout: page

readme_index:
  remove_originals: true
  with_frontmatter: false
optional_front_matter:
  remove_originals: true

remote_theme: hmua/Customized-Minima
