title: “Jekyll 4”学习
description: 谢谢你！
include:
  - '_test_include.yml'

tweets:
  - 2022:
    - 6:
      - 16:
          data from config
          y22 m6 d16
          some content
      - 17:
          y22m6d17 y22m6d17
  - 2023:
    - 6:
      - 16:
          some content
          1616 16 16
      - 17:
          17171717
          some content 2
          some content 333

site_field: '1245'
site_array:
  - site array 123
  - 456

collections:
  测试集合2:
    type: post
    post: true
    output: true
  test_collection:
    type: post
    post: true
    output: true
  测试集合1:
    type: post
    post: true
    output: true

defaults:
  - scope:
      path: _测试集合1/_posts
    values:
      output: true
      layout: post

  - scope:
      path: ""
      type: "测试集合1"
    values:
      layout: page
  - scope:
      path: README.md
    values:
      layout: home
  - scope:
      path:
    values:
      layout: page

readme_index:
  remove_originals: true
  with_frontmatter: false
optional_front_matter:
  remove_originals: true
#省略fm的页面和不省略的会有区别，引用到的其他页面的content，
#没有front matter的，引用到的是Liquid build后的Markdown，
#有front matter的，引用到的则有一些页是未build的“Liquid原文”，一些页是build后的，
#以本页为分界，从本页引用本页开始，本页和之后全是未build的，
所以似乎和这个plugin无关。

remote_theme: hmua/Customized-Minima
